---
- name: "Issue a certificate for each domains: {{ item }}"
  shell: "certbot --nginx -d {{ item }} --noninteractive --agree-tos --redirect --email {{ certbot_admin_email }}"
  become: true
  notify: reload nginx
